source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.0.5'
gem 'sqlite3'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'bootstrap-sass', '~> 3.3.6'

gem 'devise','~> 4.2' # Forms
gem 'toastr-rails', '~> 1.0'
gem 'figaro', '~> 1.1', '>=1.1.1'
gem 'omniauth', '~> 1.6'
gem 'omniauth-facebook', '~> 4.0' # Using Facebook for Login & Signup

gem 'paperclip', '~> 5.1.0' # For Adding Images to Site
gem 'aws-sdk', '~> 2.8' # AWS (Amazon Web Service)
gem 'geocoder', '~> 1.4' # Google Maps
gem 'jquery-ui-rails', '~> 5.0' # jQuery Date Picker

group :development, :test do
  gem 'byebug', platform: :mri
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]


# //////////////////////////////////////////////////////////////////////////////////////////////////
# //  DEVISE(gem):
# //  Simply Devise is a flexible authentication solution for Rails based on Warden. It:
# //  Is Rack based.
# //  Is a complete MVC solution based on Rails engines.
# //  Allows you to have multiple roles (or models/scopes) signed in at the same time.
# //  Is based on a modularity concept: use just what you really need.
# //////////////////////////////////////////////////////////////////////////////////////////////////

# //////////////////////////////////////////////////////////////////////////////////////////////////
# //  OmniAuth is a gem that provides authentication using third-party credentials such as
# //  Facebook, Twitter, or GitHub accounts.
# //////////////////////////////////////////////////////////////////////////////////////////////////

# //////////////////////////////////////////////////////////////////////////////////////////////////
# //  PAPERCLIP(gem):
# //  Provided by thoughtbot.
# //  File attachment manager.
# //  It was created to make file attachment very easy.
# //////////////////////////////////////////////////////////////////////////////////////////////////

# //////////////////////////////////////////////////////////////////////////////////////////////////
# //  brew install imagemagick
# //////////////////////////////////////////////////////////////////////////////////////////////////
