# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3b191fc2357393402113a3a4a581dd568e441f834f585a25a389d44f7f3dcbf78d6aa8ef71165a81dfc4bb17e8b4e5ff8a1ec8c7692e5725dce9fc61edff015

test:
  secret_key_base: 9c572f312518ec0d035eaa1f4f77d3bd251248af2187658466c9cc1f8104a850bc6ad51a17d2d8c1f32191ef012ca16dc1314d3a1e149dfe20ba0b322f567918

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
